/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlobId = string;
export interface LoginResponse { 'userId' : string, 'role' : UserRole }
export interface Passage {
  'id' : PassageId,
  'title' : string,
  'content' : string,
  'gradeLevel' : bigint,
}
export type PassageId = bigint;
export interface PassageInfo {
  'id' : PassageId,
  'title' : string,
  'content' : string,
  'subject' : string,
  'gradeLevel' : bigint,
}
export type ResultId = bigint;
export interface ScoreRecord {
  'wpm' : bigint,
  'weekNumber' : bigint,
  'comprehensionScore' : bigint,
  'rhythmScore' : bigint,
  'fluencyScore' : bigint,
  'pronunciationScore' : bigint,
}
export interface SkillScores {
  'chunking' : bigint,
  'pronunciation' : bigint,
  'intonation' : bigint,
  'rhythm' : bigint,
}
export interface StudentLevel {
  'enrolledGrade' : bigint,
  'effectiveLevel' : bigint,
}
export interface StudentProgressSummary {
  'studentId' : UserId,
  'name' : string,
  'latestComprehensionScore' : bigint,
  'latestWPM' : bigint,
  'weeklyTrend' : Array<bigint>,
  'grade' : bigint,
  'isBehind' : boolean,
}
export interface TestResult {
  'id' : ResultId,
  'studentId' : UserId,
  'answers' : Array<bigint>,
  'audioBlobId' : [] | [ExternalBlobId],
  'score' : bigint,
  'timestamp' : bigint,
  'passageId' : PassageId,
}
export interface User {
  'id' : UserId,
  'username' : string,
  'password' : string,
  'role' : UserRole,
  'grade' : [] | [bigint],
  'teacherId' : [] | [UserId],
}
export type UserId = string;
export interface UserProfile {
  'username' : string,
  'userId' : UserId,
  'role' : UserRole,
  'grade' : [] | [bigint],
  'effectiveLevel' : [] | [bigint],
}
export type UserRole = { 'admin' : null } |
  { 'teacher' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VocabMastery {
  'mastered' : boolean,
  'word' : string,
  'grade' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addScoreHistory' : ActorMethod<[UserId, ScoreRecord], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createStudent' : ActorMethod<[string, string, bigint], UserId>,
  'createStudentWithCreds' : ActorMethod<
    [string, string, string, string, bigint],
    UserId
  >,
  'createTeacher' : ActorMethod<[string, string], UserId>,
  'createTeacherWithCreds' : ActorMethod<[string, string, string], UserId>,
  'ensureClassio1Admin' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getClassProgress' : ActorMethod<[UserId], Array<StudentProgressSummary>>,
  'getPassageForGrade' : ActorMethod<[bigint], [] | [Passage]>,
  'getPassageForStudent' : ActorMethod<[UserId], [] | [PassageInfo]>,
  'getResultsForStudent' : ActorMethod<[UserId], Array<TestResult>>,
  'getScoreHistory' : ActorMethod<[UserId], Array<ScoreRecord>>,
  'getStudentEffectiveLevel' : ActorMethod<[UserId], StudentLevel>,
  'getStudentResults' : ActorMethod<[UserId], Array<TestResult>>,
  'getStudentResultsWithCreds' : ActorMethod<
    [string, string, UserId],
    Array<TestResult>
  >,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getVocabMastery' : ActorMethod<[UserId], Array<VocabMastery>>,
  'initializeSystem' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyStudents' : ActorMethod<[], Array<User>>,
  'listStudentsWithCreds' : ActorMethod<[string, string], Array<User>>,
  'listTeachers' : ActorMethod<[], Array<User>>,
  'listTeachersWithCreds' : ActorMethod<[string], Array<User>>,
  'login' : ActorMethod<[string, string], LoginResponse>,
  'logout' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitTest' : ActorMethod<
    [UserId, PassageId, Array<bigint>, [] | [ExternalBlobId]],
    bigint
  >,
  'submitTestWithSkills' : ActorMethod<
    [UserId, PassageId, SkillScores, [] | [ExternalBlobId]],
    bigint
  >,
  'updateVocabMastery' : ActorMethod<
    [UserId, string, bigint, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];