/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'teacher' : IDL.Null,
  'student' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'userId' : UserId,
  'role' : UserRole,
  'grade' : IDL.Opt(IDL.Nat),
});
export const ResultId = IDL.Nat;
export const ExternalBlobId = IDL.Text;
export const PassageId = IDL.Nat;
export const TestResult = IDL.Record({
  'id' : ResultId,
  'studentId' : UserId,
  'answers' : IDL.Vec(IDL.Nat),
  'audioBlobId' : IDL.Opt(ExternalBlobId),
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'passageId' : PassageId,
});
export const Passage = IDL.Record({
  'id' : PassageId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'gradeLevel' : IDL.Nat,
});
export const QuestionId = IDL.Nat;
export const Question = IDL.Record({
  'id' : QuestionId,
  'correctIndex' : IDL.Nat,
  'questionText' : IDL.Text,
  'passageId' : PassageId,
  'options' : IDL.Vec(IDL.Text),
});
export const User = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'role' : UserRole,
  'grade' : IDL.Opt(IDL.Nat),
  'teacherId' : IDL.Opt(UserId),
});
export const LoginResponse = IDL.Record({
  'userId' : IDL.Text,
  'role' : UserRole,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [UserId], []),
  'createTeacher' : IDL.Func([IDL.Text, IDL.Text], [UserId], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMyResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
  'getPassageForGrade' : IDL.Func([IDL.Nat], [IDL.Opt(Passage)], ['query']),
  'getQuestionsForPassage' : IDL.Func(
      [PassageId],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getStudentResults' : IDL.Func([UserId], [IDL.Vec(TestResult)], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'initializeSystem' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyStudents' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'listTeachers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResponse], []),
  'logout' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitTest' : IDL.Func(
      [PassageId, IDL.Vec(IDL.Nat), IDL.Opt(ExternalBlobId)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'teacher' : IDL.Null,
    'student' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'userId' : UserId,
    'role' : UserRole,
    'grade' : IDL.Opt(IDL.Nat),
  });
  const ResultId = IDL.Nat;
  const ExternalBlobId = IDL.Text;
  const PassageId = IDL.Nat;
  const TestResult = IDL.Record({
    'id' : ResultId,
    'studentId' : UserId,
    'answers' : IDL.Vec(IDL.Nat),
    'audioBlobId' : IDL.Opt(ExternalBlobId),
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'passageId' : PassageId,
  });
  const Passage = IDL.Record({
    'id' : PassageId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'gradeLevel' : IDL.Nat,
  });
  const QuestionId = IDL.Nat;
  const Question = IDL.Record({
    'id' : QuestionId,
    'correctIndex' : IDL.Nat,
    'questionText' : IDL.Text,
    'passageId' : PassageId,
    'options' : IDL.Vec(IDL.Text),
  });
  const User = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'role' : UserRole,
    'grade' : IDL.Opt(IDL.Nat),
    'teacherId' : IDL.Opt(UserId),
  });
  const LoginResponse = IDL.Record({ 'userId' : IDL.Text, 'role' : UserRole });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createStudent' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [UserId], []),
    'createTeacher' : IDL.Func([IDL.Text, IDL.Text], [UserId], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMyResults' : IDL.Func([], [IDL.Vec(TestResult)], ['query']),
    'getPassageForGrade' : IDL.Func([IDL.Nat], [IDL.Opt(Passage)], ['query']),
    'getQuestionsForPassage' : IDL.Func(
        [PassageId],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getStudentResults' : IDL.Func([UserId], [IDL.Vec(TestResult)], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'initializeSystem' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyStudents' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'listTeachers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResponse], []),
    'logout' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitTest' : IDL.Func(
        [PassageId, IDL.Vec(IDL.Nat), IDL.Opt(ExternalBlobId)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };